# Generated by Django 5.1.3 on 2025-02-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hireforadmin_alter_hire_budget_alter_hire_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predicthire',
            name='HireA_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_hires', to='myapp.hireforadmin'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='Budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hire',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hires', to='myapp.member'),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='Budget',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='Chair',
            field=models.IntegerField(default=0, verbose_name='Chair'),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='HireC_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predict_hires', to='myapp.hire'),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='Lighting',
            field=models.IntegerField(default=0, verbose_name='Lighting (pc.)'),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='Nail',
            field=models.IntegerField(default=0, verbose_name='Nail (box.)'),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='Table',
            field=models.IntegerField(default=0, verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='predicthire',
            name='Wood',
            field=models.IntegerField(default=0, verbose_name='Wood (pc.)'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('Resource_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Width', models.FloatField()),
                ('Length', models.FloatField()),
                ('Height', models.FloatField()),
                ('Type', models.CharField(max_length=100)),
                ('Location', models.CharField(blank=True, max_length=150, null=True)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Wood_P', models.IntegerField(default=0, verbose_name='Wood (pc.) Predict')),
                ('Lighting_P', models.IntegerField(default=0, verbose_name='Lighting (pc.) Predict')),
                ('Nail_P', models.IntegerField(default=0, verbose_name='Nail (box.) Predict')),
                ('Table_P', models.IntegerField(default=0, verbose_name='Table Predict')),
                ('Chair_P', models.IntegerField(default=0, verbose_name='Chair Predict')),
                ('Wood', models.IntegerField(default=0, verbose_name='Wood (pc.) Actual')),
                ('Lighting', models.IntegerField(default=0, verbose_name='Lighting (pc.) Actual')),
                ('Nail', models.IntegerField(default=0, verbose_name='Nail (box.) Actual')),
                ('Table', models.IntegerField(default=0, verbose_name='Table Actual')),
                ('Chair', models.IntegerField(default=0, verbose_name='Chair Actual')),
                ('Predict_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='myapp.predicthire')),
            ],
        ),
    ]
